# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Install uv
FROM python:3.12-slim

# Install tini
RUN apt-get update && \
    apt-get install -y --no-install-recommends tini && \
    rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Change the working directory to the `app` directory
WORKDIR /app

# Copy the lockfile and `pyproject.toml` into the image
COPY uv.lock /app/uv.lock
COPY pyproject.toml /app/pyproject.toml

# Install dependencies
RUN uv sync --frozen --no-install-project --no-dev

# Copy the project into the image
COPY . /app

# Sync the project and install it
RUN uv sync --frozen --no-dev

# Use the installed CLI directly instead of uv run to avoid rebuilds
ENV PATH="/app/.venv/bin:$PATH"

# Run the server
ENTRYPOINT ["tini", "--", "openai-image-gen-edit"]
CMD ["stdio"]
